### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by HXM4Tech** [KaliMasterDev/cHEXAos#1]
- [x] Create basic ASM bootcode
- [x] Load C code
- [x] Add print function and sysklog
- [x] Add kernel panic
- [ ] Add hardware interrupts
- [ ] Add keyboard driver
- [ ] Add input function
- [ ] Create built-in kernel shell
- [ ] Add basic programming language interpreter
- [ ] Add any filesystem
- [ ] Create libraries
- [ ] Add loading binary files
- [ ] Add config files
- [ ] Add more file systems
- [ ] Add multi-tasking
- [ ] Create system deamon
- [ ] Add networking

**Comment by maalos** [comment]
chętnie z kilkoma pomogę 😄
